DWAPlannerROS:
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  acc_lim_th: 1.0
  max_trans_vel: 0.3
  min_trans_vel: 0.05
  max_vel_x: 0.3
  min_vel_x: -0.05
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_rot_vel: 0.8
  min_rot_vel: 0.2

  yaw_goal_tolerance: 0.2
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: true

  sim_time: 1.2
  sim_granularity: 0.2
  vx_samples: 4
  vtheta_samples: 10

